build:
  name: python
  version: "3.12"

services:
  - type: web
    name: edith-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres.klcyvfjilvewegsahgei:Rishiteja%402102@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres